name: Publish to GitHub Packages

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "2.1.3"

      - name: Configure Poetry for GitHub Packages
        run: |
          poetry config repositories.github https://maven.pkg.github.com/${{ github.repository }}
          poetry config http-basic.github ${{ github.actor }} ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Build package
        run: |
          poetry build

      - name: Publish to GitHub Packages
        run: |
          poetry publish --repository github

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/